### ISSUE TITLE
The windows logic in std/path breaks in DNT

### ISSUE THREAD

**Issue by oscarotero** [denoland/std#5468]
**Describe the bug**

I want to publish [a package](https://github.com/ventojs/vento) to NPM using DNT. It worked fine until now. After updating `@std/path` from 0.225.2 to 1.0.0, the build process breaks:

```
[dnt] Building project...
[dnt] Type checking ESM...
src/deps/jsr.io/@std/path/1.0.0/_os.ts:25:6 - error TS2304: Cannot find name 'navigator'.

25     (navigator.userAgent.includes("Win") ? "windows" : "linux");
        ~~~~~~~~~

error: Uncaught (in promise) Error: Had 1 diagnostics.
          throw new Error(`Had ${diagnostics.length} diagnostics.`);
                ^
    at getProgramAndMaybeTypeCheck (https://jsr.io/@deno/dnt/0.41.2/mod.ts:468:17)
    at build (https://jsr.io/@deno/dnt/0.41.2/mod.ts:354:17)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///Users/oscarotero/www/ventojs/vento/_scripts/build_npm.ts:12:1
```

**Steps to Reproduce**

1. Clone the repository https://github.com/ventojs/vento
2. Run `deno task build-npm 1.12.10`

**Expected behavior**

The build is done successfully

**Environment**

- OS: MacOS 12.7.5
- deno version: 1.45.2
- std version: @std/path@1.0.0

**Comment by iuioiua** [comment]
This is likely an issue with the build script. Try adding `lib: ["ESNext", "DOM"]` to your `compilerOptions` parameter. Please feel free to re-open if this issue persists.

**Comment by kt3k** [comment]
It seems we used to cast globalThis to any before accessing to navigator https://github.com/denoland/std/blob/release-2024.06.03/path/_os.ts#L27

dnt probably checks types with `@types/node` settings. (Deno and DOM both have global `navigator`)
